import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import path from 'path';
const url = process.argv[2];
const shots = process.argv[3];
const browser = await chromium.launch({ args: ['--allow-file-access-from-files', '--autoplay-policy=user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('console', m => { if (m.type() === 'error' || m.type() === 'warning') errors.push(m.text()); });
page.on('pageerror', e => errors.push('pageerror: ' + e.message));
const t0 = Date.now();
await page.goto(url);
await page.waitForFunction(() => window.PLAYER && window.PLAYER.state.ready, null, { timeout: 120000 });
console.log('ready after', Date.now() - t0, 'ms; audio failed?', await page.evaluate(() => PLAYER.Sound.failed), 'buffer s', await page.evaluate(() => PLAYER.Sound.buffer && PLAYER.Sound.buffer.duration));
await page.screenshot({ path: shots + '_cover.png' });
await page.click('#begin');
await page.waitForTimeout(2500);
const a = await page.evaluate(() => ({ t: PLAYER.Sound.time(), playing: PLAYER.state.playing, ctx: PLAYER.Sound.ctx && PLAYER.Sound.ctx.state }));
console.log('after 2.5s:', a);
await page.keyboard.press('Space');
await page.waitForTimeout(600);
const b = await page.evaluate(() => ({ t: PLAYER.Sound.time(), playing: PLAYER.state.playing }));
await page.waitForTimeout(600);
const b2 = await page.evaluate(() => PLAYER.Sound.time());
console.log('paused:', b, 'still', b2);
await page.evaluate(() => PLAYER.seek(46.2));
await page.screenshot({ path: shots + '_seek.png' });
await page.keyboard.press('Space');
await page.waitForTimeout(1000);
console.log('resumed at ~46.2 ->', await page.evaluate(() => PLAYER.Sound.time()));
await page.evaluate(() => PLAYER.seek(59.3));
await page.waitForTimeout(1500);
console.log('end state:', await page.evaluate(() => ({ playing: PLAYER.state.playing, replayCard: !document.getElementById('replayCard').hidden, t: PLAYER.Sound.time() })));
await page.screenshot({ path: shots + '_end.png' });
await page.keyboard.press('r');
await page.waitForTimeout(800);
console.log('replay ->', await page.evaluate(() => ({ t: PLAYER.Sound.time(), playing: PLAYER.state.playing })));
// frame rate while playing (headless, software raster)
const fps = await page.evaluate(() => new Promise(res => { let n = 0; const s = performance.now(); function f() { n++; if (performance.now() - s < 2000) requestAnimationFrame(f); else res(n / 2); } requestAnimationFrame(f); }));
console.log('rAF rate while playing (headless software):', fps);
console.log('errors:', errors);
await browser.close();
