// Generated by tools/build_cues.py - narration placement, word timings and subtitles.
window.CUES = {
 "duration": 60.0,
 "lines": {
  "L0": {
   "start": 0.35,
   "speechStart": 0.675,
   "speechEnd": 4.1,
   "end": 4.4
  },
  "L1": {
   "start": 5.9,
   "speechStart": 6.225,
   "speechEnd": 13.625,
   "end": 13.95
  },
  "L2": {
   "start": 14.4,
   "speechStart": 14.725,
   "speechEnd": 16.7,
   "end": 17.05
  },
  "L3": {
   "start": 16.9,
   "speechStart": 17.225,
   "speechEnd": 18.95,
   "end": 19.275
  },
  "L4": {
   "start": 19.8,
   "speechStart": 20.075,
   "speechEnd": 23.025,
   "end": 23.325
  },
  "L5": {
   "start": 27.2,
   "speechStart": 27.525,
   "speechEnd": 33.175,
   "end": 33.5
  },
  "L6": {
   "start": 35.4,
   "speechStart": 35.7,
   "speechEnd": 38.85,
   "end": 39.3
  },
  "L7": {
   "start": 43.05,
   "speechStart": 43.35,
   "speechEnd": 44.25,
   "end": 44.575
  },
  "L8": {
   "start": 47.6,
   "speechStart": 47.875,
   "speechEnd": 50.7,
   "end": 51.025
  },
  "L9": {
   "start": 51.6,
   "speechStart": 51.9,
   "speechEnd": 57.15,
   "end": 57.475
  }
 },
 "words": {
  "L0": [
   [
    "In",
    0.675,
    0.762
   ],
   [
    "which",
    0.762,
    0.987
   ],
   [
    "Pooh",
    0.987,
    1.275
   ],
   [
    "plans",
    1.275,
    1.588
   ],
   [
    "a",
    1.588,
    1.65
   ],
   [
    "picnic",
    1.65,
    2.275
   ],
   [
    "and",
    2.35,
    2.462
   ],
   [
    "the",
    2.462,
    2.55
   ],
   [
    "wind",
    2.55,
    2.825
   ],
   [
    "comes",
    2.825,
    3.162
   ],
   [
    "too",
    3.162,
    4.1
   ]
  ],
  "L1": [
   [
    "One",
    6.225,
    6.45
   ],
   [
    "breezy",
    6.45,
    6.825
   ],
   [
    "morning",
    6.825,
    7.225
   ],
   [
    "Pooh",
    7.313,
    7.575
   ],
   [
    "laid",
    7.575,
    7.787
   ],
   [
    "out",
    7.787,
    7.938
   ],
   [
    "a",
    7.938,
    8.0
   ],
   [
    "picnic",
    8.0,
    8.975
   ],
   [
    "a",
    9.112,
    9.225
   ],
   [
    "cloth",
    9.225,
    9.625
   ],
   [
    "a",
    9.663,
    9.725
   ],
   [
    "pot",
    9.725,
    9.937
   ],
   [
    "of",
    9.937,
    10.05
   ],
   [
    "honey",
    10.05,
    10.5
   ],
   [
    "and",
    11.025,
    11.137
   ],
   [
    "a",
    11.137,
    11.2
   ],
   [
    "space",
    11.2,
    11.662
   ],
   [
    "just",
    11.662,
    11.912
   ],
   [
    "the",
    11.912,
    12.012
   ],
   [
    "size",
    12.012,
    12.387
   ],
   [
    "of",
    12.387,
    12.462
   ],
   [
    "a",
    12.462,
    12.525
   ],
   [
    "Piglet",
    12.525,
    13.625
   ]
  ],
  "L2": [
   [
    "For",
    14.725,
    14.95
   ],
   [
    "me",
    14.95,
    15.225
   ],
   [
    "asked",
    15.325,
    15.7
   ],
   [
    "Piglet",
    15.7,
    16.7
   ]
  ],
  "L3": [
   [
    "For",
    17.225,
    17.45
   ],
   [
    "us",
    17.45,
    17.75
   ],
   [
    "said",
    17.825,
    18.075
   ],
   [
    "Pooh",
    18.075,
    18.95
   ]
  ],
  "L4": [
   [
    "But",
    20.075,
    20.2
   ],
   [
    "the",
    20.2,
    20.337
   ],
   [
    "wind",
    20.337,
    20.775
   ],
   [
    "it",
    20.812,
    20.963
   ],
   [
    "seemed",
    20.963,
    21.375
   ],
   [
    "wanted",
    21.425,
    21.75
   ],
   [
    "to",
    21.75,
    21.85
   ],
   [
    "come",
    21.85,
    22.112
   ],
   [
    "too",
    22.112,
    23.025
   ]
  ],
  "L5": [
   [
    "So",
    27.525,
    27.675
   ],
   [
    "off",
    27.675,
    27.875
   ],
   [
    "they",
    27.875,
    28.025
   ],
   [
    "went",
    28.025,
    28.525
   ],
   [
    "over",
    28.625,
    28.875
   ],
   [
    "the",
    28.875,
    28.975
   ],
   [
    "heather",
    28.975,
    29.3
   ],
   [
    "and",
    29.3,
    29.425
   ],
   [
    "under",
    29.425,
    29.662
   ],
   [
    "the",
    29.662,
    29.75
   ],
   [
    "pines",
    29.75,
    30.3
   ],
   [
    "with",
    30.338,
    30.463
   ],
   [
    "the",
    30.463,
    30.55
   ],
   [
    "bees",
    30.55,
    30.85
   ],
   [
    "close",
    30.85,
    31.175
   ],
   [
    "behind",
    31.175,
    31.725
   ],
   [
    "just",
    31.8,
    32.038
   ],
   [
    "in",
    32.038,
    32.175
   ],
   [
    "case",
    32.175,
    33.175
   ]
  ],
  "L6": [
   [
    "Perhaps",
    35.7,
    36.2
   ],
   [
    "said",
    36.275,
    36.525
   ],
   [
    "Pooh",
    36.525,
    36.875
   ],
   [
    "it",
    37.025,
    37.125
   ],
   [
    "knows",
    37.125,
    37.425
   ],
   [
    "somewhere",
    37.425,
    37.775
   ],
   [
    "nicer",
    37.775,
    38.85
   ]
  ],
  "L7": [
   [
    "It",
    43.35,
    43.55
   ],
   [
    "did",
    43.55,
    44.25
   ]
  ],
  "L8": [
   [
    "It",
    47.875,
    48.025
   ],
   [
    "wasn't",
    48.025,
    48.35
   ],
   [
    "quite",
    48.35,
    48.675
   ],
   [
    "the",
    48.675,
    48.775
   ],
   [
    "picnic",
    48.775,
    49.2
   ],
   [
    "Pooh",
    49.2,
    49.45
   ],
   [
    "had",
    49.45,
    49.625
   ],
   [
    "planned",
    49.625,
    50.7
   ]
  ],
  "L9": [
   [
    "But",
    51.9,
    52.075
   ],
   [
    "with",
    52.075,
    52.288
   ],
   [
    "Piglet",
    52.288,
    52.775
   ],
   [
    "beside",
    52.775,
    53.3
   ],
   [
    "him",
    53.3,
    53.875
   ],
   [
    "it",
    53.988,
    54.113
   ],
   [
    "was",
    54.113,
    54.238
   ],
   [
    "a",
    54.238,
    54.35
   ],
   [
    "perfectly",
    54.35,
    55.087
   ],
   [
    "wonderful",
    55.087,
    55.712
   ],
   [
    "afternoon",
    55.712,
    57.15
   ]
  ]
 },
 "subtitles": [
  {
   "line": "L1",
   "start": 6.1,
   "end": 10.86,
   "text": "One breezy morning, Pooh laid out a picnic:\na cloth, a pot of honey,"
  },
  {
   "line": "L1",
   "start": 10.91,
   "end": 14.07,
   "text": "and a space just the size of a Piglet."
  },
  {
   "line": "L2",
   "start": 14.61,
   "end": 17.06,
   "text": "“For me?” asked Piglet."
  },
  {
   "line": "L3",
   "start": 17.11,
   "end": 19.4,
   "text": "“For us,” said Pooh."
  },
  {
   "line": "L4",
   "start": 19.95,
   "end": 23.47,
   "text": "But the wind, it seemed,\nwanted to come too."
  },
  {
   "line": "L5",
   "start": 27.4,
   "end": 30.17,
   "text": "So off they went, over the heather\nand under the pines,"
  },
  {
   "line": "L5",
   "start": 30.22,
   "end": 33.62,
   "text": "with the bees close behind,\njust in case."
  },
  {
   "line": "L6",
   "start": 35.58,
   "end": 39.3,
   "text": "“Perhaps,” said Pooh,\n“it knows somewhere nicer.”"
  },
  {
   "line": "L7",
   "start": 43.23,
   "end": 44.7,
   "text": "It did."
  },
  {
   "line": "L8",
   "start": 47.76,
   "end": 51.15,
   "text": "It wasn’t quite the picnic Pooh had planned."
  },
  {
   "line": "L9",
   "start": 51.78,
   "end": 57.6,
   "text": "But with Piglet beside him,\nit was a perfectly wonderful afternoon."
  }
 ]
};
